name: Testar Envio Juninho News para Telegram (Manual)

on:
  workflow_dispatch: # Permite que este workflow seja acionado manualmente

jobs:
  test-and-send-news-now: # Nome do job
    runs-on: ubuntu-latest # Usa a última versão estável do Ubuntu
    steps:
      - name: Checkout do código do repositório
        uses: actions/checkout@v4 # Ação para baixar seu código

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Especifique a versão do Python que seu script usa

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executar script Juninho News para Teste
        env: # Define as variáveis de ambiente para o script Python
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }} # Certifique-se de que este secret existe se seu script o usa
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python juninho_news_bot.py # Garanta que o nome do arquivo .py está correto
